version: '2'
services:
  loantrackingapplication-app:
    image: loantrackingapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://loantrackingapplication-mssql:1433;database=LoanTrackingApplication
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  loantrackingapplication-mssql:
    extends:
      file: mssql.yml
      service: loantrackingapplication-mssql
